project_id = "tjazosfjsxqaaspwsgal"

[functions.fetch-nfl-data]
verify_jwt = false

# Run every 5 minutes during NFL game hours
[functions.fetch-nfl-data.cron]
schedule = "*/5 * * * *"

[functions.export-game-data]
verify_jwt = true

[functions.export-play-by-play]
verify_jwt = true

[functions.halftime-emailer]
verify_jwt = false

# Run every 5 minutes during NFL game hours
[functions.halftime-emailer.cron]
schedule = "*/5 * * * *"